name: Auto merge PR's

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - edited
      - synchronize

# Target branch: ${{ github.event.pull_request.base.ref }}
# Source branch: ${{ github.event.pull_request.head.ref }}

jobs:
  automerge-nonprod:
    name: Automerge [non-prod]
    if: >
      github.event.pull_request.base.ref != 'prod' &&
      contains(github.event.pull_request.labels.*.name, 'auto merge')
    runs-on: ubuntu-latest
    steps:
    
      # If NOT on devel, wait for checks on SELF to finish:
      - name: 'Wait for action suite'
        if: github.event.pull_request.base.ref != 'devel'
        uses: "WyriHaximus/github-action-wait-for-status@v1.3"
        id: waitforstatuschecks
        with:
          checkInterval: 10
          ignoreActions: "Automerge [non-prod]"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # If something in the suite FAILED, break off now:
      - name: 'Check success of action suite'
        # special catch for devel, since it doesn't need to wait to merge
        if: >
          github.event.pull_request.base.ref != 'devel' &&
          steps.waitforstatuschecks.outputs.status != 'success'
        run: false

      # Finally merge the PR:
      - name: 'Merge to Branch'
        uses: "pascalgn/automerge-action@v0.13.1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: auto merge
          UPDATE_LABELS: auto merge

  automerge-prod:
    name: Automerge [prod]
    if: >
      github.event.pull_request.base.ref == 'prod' &&
      contains(github.event.pull_request.labels.*.name, 'auto merge')
    runs-on: ubuntu-latest
    steps:
      - name: "Testing only gets hit when merging to prod"
        run: false
