name: Auto merge PR's

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - edited
      - synchronize

jobs:
  automerge:
    name: Automerge [prod]
    if: >
      github.event.pull_request.base.ref == 'prod' &&
      contains(github.event.pull_request.labels.*.name, 'auto merge')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        merge_to_branch: [devel, test]
    steps:

      # Setup Git:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.merge_to_branch }}

      # Change what is in the PR
      - name: Reset branch to ${head_of_pr}
        run: |
          git fetch origin ${head_of_pr}:${head_of_pr}
          git reset --hard ${head_of_pr}
        env:
          head_of_pr: ${{ github.event.pull_request.head.ref }}

      # Open PR to target branch:
      - name: "Open PR to ${{ matrix.merge_to_branch }}"
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}
          base: ${{ matrix.merge_to_branch }}
          title: "Automatic merge triggered from ${{ github.event.pull_request.head.ref }} to ${{ matrix.merge_to_branch }}"
          # Taking off automerge temp, to track what's happening easier:
          labels: 'dependancies'
          # labels: 'auto merge, dependancies'
      
      ### NOTE: Rest of actions only run on test branch
      # If you add more after this point, make sure it has:
      # if: ${{ matrix.merge_to_branch }} == 'test'


      - if: matrix.merge_to_branch == 'test'
        name: Save the latest commit
        id: get-latest-commit
        run: echo "::set-output name=commit::$(git rev-parse HEAD)"

      - if: matrix.merge_to_branch == 'test'
        name: Wait for test to finish
        uses: jitterbit/await-check-suites@v1
        with:
          author: ASF-Discovery <uaf-asf-discovery@alaska.edu>
          ref: ${{ steps.get-latest-commit.outputs.commit }}
          intervalSeconds: 10
          timeoutSeconds: 300
          failStepIfUnsuccessful: true
      
      # TODO:
      # take off auto merge label
      # Assign reviewers



