name: Label the PR

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - prod
      - test
      - devel

jobs:
  bump-label:
    runs-on: ubuntu-latest
    steps:
      - name: Require Version Label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "major, minor, patch, bumpless" 