name: Run test suite

on: [pull_request, push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # temp disabling, about to merge 30+ PR's, and don't want suite to
      # run for *every* single one of them:
      - run: echo "TEMP DISABLED"


      # # Get the code:
      # - uses: actions/checkout@v2
      # # Run the local action:
      # - uses: ./.github/actions/pytest-automation
      #   with:
      #     PYTEST_OPTIONS: -n auto