name: Runs the test suite

on:
  pull_request:
    branches:
      - prod
      - test
      - devel

jobs:
  run-test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./actions
