name: Runs the test suite

# Push also gets triggered on pull requests:
on: pull_request

jobs:
  run-test-suite:
    runs-on: ubuntu-latest
    steps:
      # Get the code:
      - uses: actions/checkout@v1
      # Run the local action:
      - uses: ./.github/actions/pytest-automation
