name: Runs the test suite

on:
  # All pushes. (colon w/ no key means all defaults)
  push:
  # Just pull requests from these branches:
  pull_request:
    branches:
      - prod
      - test
      - devel


jobs:
  run-test-suite:
    runs-on: ubuntu-latest
    steps:
      # Get the code:
      - uses: actions/checkout@v1
      # Run the local action:
      - uses: ./.github/actions/pytest-automation
