name: Run test suite

on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: debug info
        run: |
          echo "Branch: ${GITHUB_REF}"
          
      # Get the code:
      - uses: actions/checkout@v2
      # Run the local action:
      - uses: ./.github/actions/pytest-automation
        with:
          PYTEST_OPTIONS: -n auto