name: Run Pytest Suite

on:
  push:
    branches:
      - prod
      - test
      - devel

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-xdist

    - name: Run the Suite
      run: |
        git clone --branch prod https://github.com/asfadmin/Discovery-PytestAutomation
        cd Discovery-PytestAutomation
        pytest -s .